### ISSUE TITLE
Handshake problem [All posts here]

### ISSUE THREAD

**Issue by deltaxflux** [deltaxflux/fluxion#328]
Here is the official post for this problem. It is more or less a problem with pyrit. 

Step 1. Analyze the cap file
`pyrit -r file.cap analyze`

_What it should look like_

> Pyrit 0.4.0 (C) 2008-2011 Lukas Lueg http://pyrit.googlecode.com
This code is distributed under the GNU General Public License v3+
Parsing file '<obscured>.cap' (1/1)...
Parsed 1 packets (1 802.11-packets), got 1 AP(s)
#1: AccessPoint <obscured> ('TP-LINK_<obscured>'):
No valid EAOPL-handshake + ESSID detected.

_Here is the output of a truncated cap_
>Parsing file '<obscured>.cap' (1/1)...
Traceback (most recent call last):
  File "/usr/bin/pyrit", line 6, in <module>
    pyrit_cli.Pyrit_CLI().initFromArgv()
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 115, in initFromArgv
    func(self, **options)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 163, in new_f
    f(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 447, in analyze
    parser = self._getParser(capturefile)
  File "/usr/lib/python2.7/dist-packages/pyrit_cli.py", line 179, in _getParser
    parser.parse_pcapdevice(dev)
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 600, in parse_pcapdevice
    for pckt in reader:
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 500, in next
    pckt = self.read()
  File "/usr/lib/python2.7/dist-packages/cpyrit/pckttools.py", line 488, in read
    r = _cpyrit_cpu.PcapDevice.read(self)
IOError: libpcap-error while reading: truncated dump file; tried to read 414 captured bytes, only got 158

2. Solve this Problem 

`pyrit -r old.cap -o new.cap stripLive`

We use only packages which are necessary for the eapol handshake detection, and write this in a new file.

3. Analyze the new cap 

`pyrit -r new.cap analyze`

**Comment by strasharo** [comment]
This is an isssue with the current pyrit bundled with Kali:
https://github.com/JPaulMora/Pyrit/issues/500

**Comment by strasharo** [comment]
https://bugs.kali.org/view.php?id=3801
